/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./../layout/BottomNav.vue')['default']
    Cart: typeof import('./../views/Cart.vue')['default']
    CategoryList: typeof import('./../views/home/CategoryList.vue')['default']
    Home: typeof import('./../views/home/Home.vue')['default']
    Layout: typeof import('./../layout/Layout.vue')['default']
    ProductList: typeof import('./../views/products/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../views/Search.vue')['default']
    User: typeof import('./../views/User.vue')['default']
  }
}
